### ISSUE TITLE
SEO - Sitemap

### ISSUE THREAD

**Issue by adamduren** [NorthernLogic/polygigs#11]

**Comment by adamduren** [comment]
@zacharytamas What are your thoughts on how to accomplish this? My thought was a periodic cron that would generate the sitemap.xml file on the server from firebase. Definitely open to alternatives.

**Comment by zacharytamas** [comment]
That sounds like an alright approach to me. In theory postings will come and go so the sitemap would never get enormous enough to cause perf problems. It'd be nice to be wrong, though. :)
