### ISSUE TITLE
Layout improvements for front page

### ISSUE THREAD

**Issue by zacharytamas** [NorthernLogic/polygigs#5]
## General
- [ ] Update the Gig Listing layout to be more appealing and consistent (currently it looks bad on mobile and alignments are way off)

## Responsiveness
- [ ] Make the blurb text smaller on mobile.

**Comment by zacharytamas** [comment]
Should probably reassess these

**Comment by adamduren** [comment]
I think the second is still valid but the first is mostly addressed.
